### ISSUE TITLE
Scores command doesn't work with usernames that have spaces in them

### ISSUE THREAD

**Issue by MuresanSergiu** [NiceAesth/Sunny#20]
Example: s.s https://osu.ppy.sh/b/1915798 Maxim Bogdan

**Comment by AfterWind** [comment]
Possible solution would be to change everything to not support spaces (use underscores instead), otherwise, whenever we have a player name as an option it has to be the last parameter AND we have to make sure we parse that correctly

**Comment by NiceAesth** [comment]
Will be handled in the rewrite to match osu! ro bot behaviour

**Comment by NiceAesth** [comment]
Bot now uses slash commands. This fixes this behaviour. Regular commands are still available, but no longer allow spaces in input
