### ISSUE TITLE
Bot returns SHD error code (osutop command) only on my account ( redduxr - on SirohiRX)

### ISSUE THREAD

**Issue by redduxr** [NiceAesth/Sunny#25]
![Screenshot_20200120-212922~2](https://user-images.githubusercontent.com/58391079/72752941-3a8e6880-3bcc-11ea-9ec0-dede30d8b8ab.png)

**Comment by NiceAesth** [comment]
Fixed in c5e5b79c7775530c07bfafc45e92ef903fb8020a
