### ISSUE TITLE
osutop command returns error if player does not have x top play

### ISSUE THREAD

**Issue by koocieyu** [NiceAesth/Sunny#4]
Image of the issue:
![image](https://user-images.githubusercontent.com/26856087/56868157-50814b00-69f7-11e9-8044-44597aa52a85.png)

**Comment by NiceAesth** [comment]
Fixed issue in rewrite branch. Will create a PR and merge with master once other features are done.

**Comment by NiceAesth** [comment]
fixes merged into master
